Rgwy109
rsksmart/rif-notifier pull request #31
Opened 2021-02-01 13:05 UTC by vjgene

add subscription plan api
add unit tests for subscription plan api
add error tests for RSKPaymentService

2021-02-04 16:50 UTC, julianmrodri requested changes
Overal looks good left some comments and a change we need to do in the Properties.

2021-02-04 16:50 UTC, julianmrodri commented on src/main/resources/application.properties
> +rsk.blockchain.withdrawal-smart-contract-address=0x0
Here its a SINGLE contract for each operation. So you would not need to have different addresses for each method. Just live a single `notificationsManager` contract.

2021-02-04 16:50 UTC, julianmrodri commented on src/main/java/org/rif/notifier/models/DTO/SubscriptionBatchDTO.java
> +    @ApiModelProperty(notes="user wallet address.", required = true)
```suggestion
    @ApiModelProperty(notes="User wallet address.", required = true)
```

2021-02-04 16:50 UTC, julianmrodri commented on src/main/java/org/rif/notifier/models/DTO/SubscriptionBatchDTO.java
> +    @ApiModelProperty(notes="Chosen currency for payment of subscription.", required=true, example = "RIF")
```suggestion
    @ApiModelProperty(notes="Currency of the subscription.", required=true, example = "RIF")
```

2021-02-04 16:50 UTC, julianmrodri commented on src/main/java/org/rif/notifier/managers/datamanagers/SubscriptionManager.java
> +        sub.setExpirationDate(java.sql.Date.valueOf(now()));
Why are we setting `now` as expiration?

2021-02-04 16:50 UTC, julianmrodri commented on src/main/java/org/rif/notifier/controllers/SubscriptionBatchController.java
> +
```suggestion
```

2021-02-04 16:50 UTC, julianmrodri commented on src/main/java/org/rif/notifier/controllers/SubscriptionBatchController.java
> +                                        @Autowired @Qualifier("providerAddress") String providerAddress,
```suggestion
                                       @Autowired @Qualifier("providerAddress") String providerAddress,
```

2021-02-04 16:50 UTC, julianmrodri commented on README.md
> +                "hello": 1
What is this `hello`?

2021-02-04 16:50 UTC, julianmrodri commented on README.md
> +    "status": "UP",
What do you think about using more 1 for up and 0 for down? Not very happy with the "UP/DOWN" value.

2021-02-04 16:50 UTC, julianmrodri commented on README.md
> +    "status": "UP",
We can use 1 for Enabled/UP,  0 for disabled/Down

2021-02-05 12:09 UTC, vjgene commented on src/main/java/org/rif/notifier/managers/datamanagers/SubscriptionManager.java
> +        sub.setExpirationDate(java.sql.Date.valueOf(now()));
i fixed this in the new commit

2021-02-05 12:15 UTC, vjgene commented on README.md
> +                "hello": 1
this is result of handshake from db, and it's provided by spring

2021-02-05 12:28 UTC, vjgene commented on README.md
> +    "status": "UP",
this is spring default status code. I believe we can change it in configuration using management.endpoint.health.status.http-mapping.UP=1  i will check this

2021-02-05 14:56 UTC, julianmrodri approved these changes
LGTM but left some comments which need to be addresses I think

2021-02-05 14:56 UTC, julianmrodri commented on src/main/java/org/rif/notifier/services/SubscribeServices.java
> +        return false;
Why are we returning false always in this case?

2021-02-05 14:56 UTC, julianmrodri commented on src/test/java/SubscriptionProcessorJobTest.java
> +        //renewed.setExpirationDate(tomorrow);
Should we consider the case when a Subscription renewal has also expired? What happens in that case? I mean if the Renewal Subscription is already expired even before being activated.

2021-02-08 04:39 UTC, vjgene commented on src/test/java/SubscriptionProcessorJobTest.java
> +        //renewed.setExpirationDate(tomorrow);
SubscriptionProcessorJob expires all subscriptions that have reached the expiration date irrespective of their status (pending, complete, active). When renewal also expires, it will be set as expired in the database and won't be considered for notifications.

Below is the list of scenarios covered, please let me know if any other scenario to be added

1. When subscription is completed during last notification, auto renew the new subscription if there exists one,
	renew only if the new subscription is in pending status and payment is made for amount >= subscription price
	This will also set the old subscription status to complete

2. When payment event is received in blockchain, check if it has a previously active subscription, if so don't activate the new one.
	Activate the new one when payment is made, and the new subscription is in pending status

3. Scheduled job will pickup all pending subscriptions for which the payment is made, and when there is no active linked previous subscription for the given subscription. The job will then try to activate using same logic as above - only if payment is made it will activate.

	the scheduler will also make sure no expired subscriptions are activated even if payment is made.
	it will also make sure previously expired subscriptions can be activated if there is a linked renewal subscription

4. expire all subscriptions irrespective of status using scheduled job when they are past the expiration date set.

2021-02-08 04:40 UTC, vjgene commented on src/main/java/org/rif/notifier/services/SubscribeServices.java
> +        return false;
If activation criteria is matched, the result of the operation will be returned, otherwise it will return false always. I just removed the unnecessary temporary variable creation. The logic remains the same.

2021-02-08 12:37 UTC, merged