rgwy40 - add notifier CLI
rsksmart/rif-notifier pull request #44
Opened 2021-03-22 10:13 UTC by vjgene

CLI to perform basic notifier operations

2021-03-22 15:28 UTC, artem-brazhnikov requested changes
Overall looks good for a first version

2021-03-22 15:28 UTC, artem-brazhnikov commented on notifier-cli/Notifier.py
> +                resp = subprocess.run(['kill', pid])
is there a way to stop the service gracefully?

2021-03-22 15:28 UTC, artem-brazhnikov commented on notifier-cli/Notifier.py
> +            response = requests.get("http://127.0.0.1:8080/actuator/health", verify=False)
I believe there is a more effective way to access the url available. Let's save the address and port separately in a var, or 2 vars and combine the url here

2021-03-22 15:28 UTC, artem-brazhnikov commented on notifier-cli/README.MD
> + ```notifier-cli/cli.sh```
let's copy the script into a binary folder that is included in the PATH variable so a person can run the script as an application `notifier-cli`

2021-03-23 08:06 UTC, vjgene commented on notifier-cli/Notifier.py
> +                resp = subprocess.run(['kill', pid])
Actually the other way requires exposing the endpoint /actuator/shutdown which will need to be secured. so, we have to add authentication to the application in order to achieve that. Some endpoints in our app requires to work without authentication for ex. getSubscriptionPlans.

2021-03-23 09:09 UTC, vjgene commented on notifier-cli/Notifier.py
> +            response = requests.get("http://127.0.0.1:8080/actuator/health", verify=False)
This is fixed in new commit

2021-03-23 09:09 UTC, vjgene commented on notifier-cli/README.MD
> + ```notifier-cli/cli.sh```
notifier-cli command copied to /usr/local/bin

2021-03-23 09:43 UTC, artem-brazhnikov approved these changes
looks good, during this week I'll download and try using it

2021-03-23 09:43 UTC, artem-brazhnikov commented on notifier-cli/Notifier.py
> +                resp = subprocess.run(['kill', pid])
ok good

2021-03-25 16:33 UTC, merged