encrypt api notification service password and apikey
rsksmart/rif-notifier pull request #48
Opened 2021-03-29 15:50 UTC by vjgene

encrypt api notification service password and apikey

2021-03-30 11:48 UTC, artem-brazhnikov requested changes

2021-03-30 11:48 UTC, artem-brazhnikov commented on src/main/java/org/rif/notifier/managers/services/impl/APIService.java
> +        } catch(MalformedURLException e)    {
what about logging the error?

2021-03-30 15:25 UTC, vjgene commented on src/main/java/org/rif/notifier/managers/services/impl/APIService.java
> +        } catch(MalformedURLException e)    {
Added logging of error and as a precaution also disallowed invalid api urls being registered in first place.

2021-03-31 07:02 UTC, artem-brazhnikov approved these changes

2021-03-31 07:02 UTC, merged